# Builds gudhi/ci_for_gudhi on Docker Hub
FROM ubuntu:24.04

# DEBIAN_FRONTEND=noninteractive is used to prevent installation of
# package tzdata to ask for timezone
ENV DEBIAN_FRONTEND=noninteractive

# Required for Gudhi compilation
RUN apt update && apt install -y make \
    git \
    g++ \
    cmake \
    perl \
    libboost-all-dev \
    python3 \
    python3-venv \
    xz-utils \
    curl

# PEP668: work in a virtual environment
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN mkdir /home/ubuntu/install
ADD build-requirements.txt /home/ubuntu/install/
ADD test-requirements.txt /home/ubuntu/install/
RUN python -m pip install -r /home/ubuntu/install/build-requirements.txt
RUN python -m pip install -r /home/ubuntu/install/test-requirements.txt

# Try to do the same layers as Dockerfile_for_circle_ci_image_without_cgal
RUN apt install -y libeigen3-dev \
    libgmp3-dev \
    libmpfr-dev \
    libtbb-dev

ADD install_cgal.sh /home/ubuntu/install/
RUN sh /home/ubuntu/install/install_cgal.sh

# apt clean up
RUN apt autoremove && rm -rf /var/lib/apt/lists/* && rm -rf /home/ubuntu/install
