FROM ubuntu:22.04

# DEBIAN_FRONTEND=noninteractive is used to prevent installation of
# package tzdata to ask for timezone
ENV DEBIAN_FRONTEND=noninteractive

# Required for Gudhi compilation
RUN apt update && apt install -y make \
    g++ \
    cmake \
    graphviz \
    perl \
    texlive-bibtex-extra \
    biber \
    libboost-all-dev \
    libeigen3-dev \
    libgmp3-dev \
    libmpfr-dev \
    libtbb-dev \
    libcgal-dev \
    locales \
    python3 \
    python3-pip \
    python3-pytest \
    python3-tk \
    python3-pybind11 \
    libfreetype6-dev \
    pkg-config \
    curl

ADD install_cgal.sh /
RUN sh install_cgal.sh

RUN pip3 install \
    numpy \
    matplotlib \
    scipy \
    Cython \
    POT \
    scikit-learn

# apt clean up
RUN apt-get autoremove && rm -rf /var/lib/apt/lists/*

ARG GUDHI_VERSION="3.8.0"

RUN curl -LO "https://github.com/GUDHI/gudhi-devel/releases/download/tags%2Fgudhi-release-${GUDHI_VERSION}/gudhi.${GUDHI_VERSION}.tar.gz" \
&& tar xf gudhi.${GUDHI_VERSION}.tar.gz \
&& cd gudhi.${GUDHI_VERSION} \
&& mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_PYTHON=OFF -DPython_ADDITIONAL_VERSIONS=3 ..  \
&& make all test install \
&& cmake -DWITH_GUDHI_PYTHON=ON . \
&& cd python \
&& python3 setup.py install
