# Builds gudhi/ci_for_gudhi_wo_cgal on Docker Hub
FROM ubuntu:22.04

RUN apt-get update
# DEBIAN_FRONTEND=noninteractive is used to prevent installation of
# package tzdata to ask for timezone
ENV DEBIAN_FRONTEND=noninteractive

# Required for Gudhi compilation
RUN apt-get install -y make \
    git \
    g++ \
    cmake \
    perl \
    libboost-all-dev \
    python3 \
    python3-pip \
    python3-tk \
    python3-grpcio \
    libfreetype6-dev \
    pkg-config \
    curl

ADD build-requirements.txt /
ADD test-requirements.txt /

RUN pip3 install -r build-requirements.txt
RUN pip3 --no-cache-dir install -r test-requirements.txt

# Try to do the same layers as Dockerfile_for_circle_ci_image
RUN curl -LO "https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz" \
    && tar xf eigen-3.3.9.tar.gz

# apt clean up
RUN apt-get autoremove && rm -rf /var/lib/apt/lists/*
