# Builds gudhi/ci_for_gudhi on Docker Hub
FROM ubuntu:20.04

# Update and upgrade distribution
RUN apt-get update && \
    apt-get upgrade -y

# Tools necessary for installing and configuring Ubuntu
RUN apt-get install -y \
    apt-utils \
    locales \
    tzdata

# Timezone
RUN echo "Europe/Paris" | tee /etc/timezone && \
    ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

# Locale with UTF-8 support
RUN echo en_US.UTF-8 UTF-8 >> /etc/locale.gen && \
    locale-gen && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Update again
RUN apt-get update --fix-missing

# Required for Gudhi compilation
RUN apt-get install -y make \
    git \
    g++ \
    cmake \
    perl \
    libboost-all-dev \
    python3 \
    python3-pip \
    python3-tk \
    python3-grpcio \
    libfreetype6-dev \
    pkg-config \
    curl

ADD build-requirements.txt /
ADD test-requirements.txt /

RUN pip3 install -r build-requirements.txt
RUN pip3 --no-cache-dir install -r test-requirements.txt

# Try to do the same layers as Dockerfile_for_circle_ci_image_without_cgal
RUN apt-get install -y graphviz \
    texlive-full \
    biber \
    doxygen \
    libeigen3-dev \
    libgmp3-dev \
    libmpfr-dev \
    libtbb-dev

ADD install_cgal.sh /
RUN sh install_cgal.sh

# apt clean up
RUN apt-get autoremove && rm -rf /var/lib/apt/lists/*
