FROM quay.io/pypa/manylinux_2_28_x86_64:2026.09.04-1 

RUN yum -y update && yum -y install \
    curl \
    zlib-devel \
    eigen3-devel \
    mpfr-devel \
    gmp-devel \
    && yum clean all

# yum install boost-devel installs boost 1.53 and copy is the only way to install headers only boost
RUN curl -LO "https://archives.boost.io/release/1.90.0/source/boost_1_90_0.tar.gz" \
      && tar xzf boost_1_90_0.tar.gz \
      && cd boost_1_90_0 \
      && ./bootstrap.sh --prefix=/usr/local \
      && ./b2 install --prefix=/usr/local -j$(nproc) --with-headers \
      && cd .. && rm -rf boost_1_90_0 boost_1_90_0.tar.gz

COPY install_cgal.sh /
RUN chmod +x install_cgal.sh && ./install_cgal.sh

COPY build-requirements.txt /

# gudhi requires numpy >= 1.15.0, but for python >=3.10, numpy >= 2.0 is advised for package build
# and ABI compatibility with numpy 1.X and 2.X
# cf. https://numpy.org/doc/stable/dev/depending_on_numpy.html#numpy-2-0-specific-advice
RUN /opt/python/cp311-cp311/bin/python -m pip install --no-cache-dir numpy>=2.0\
&& /opt/python/cp311-cp311/bin/python -m pip install --no-cache-dir -r build-requirements.txt\
&& /opt/python/cp312-cp312/bin/python -m pip install --no-cache-dir numpy>=2.0\
&& /opt/python/cp312-cp312/bin/python -m pip install --no-cache-dir -r build-requirements.txt\
&& /opt/python/cp313-cp313/bin/python -m pip install --no-cache-dir numpy>=2.0\
&& /opt/python/cp313-cp313/bin/python -m pip install --no-cache-dir -r build-requirements.txt\
&& /opt/python/cp314-cp314/bin/python -m pip install --no-cache-dir numpy>=2.0\
&& /opt/python/cp314-cp314/bin/python -m pip install --no-cache-dir -r build-requirements.txt

ENV PYTHON311="/opt/python/cp311-cp311/"
ENV PYTHON312="/opt/python/cp312-cp312/"
ENV PYTHON313="/opt/python/cp313-cp313/"
ENV PYTHON314="/opt/python/cp314-cp314/"

ENV PATH="/opt/rh/gcc-toolset-13/root/usr/bin:${PATH}"
