# Builds gudhi/ci_for_gudhi on Docker Hub
FROM ubuntu:22.04

# DEBIAN_FRONTEND=noninteractive is used to prevent installation of
# package tzdata to ask for timezone
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
# Required for Gudhi compilation
RUN apt-get install -y make \
    git \
    g++ \
    cmake \
    graphviz \
    texlive-full \
    biber \
    doxygen \
    latexmk

# apt clean up
RUN apt-get autoremove && rm -rf /var/lib/apt/lists/*
