FROM quay.io/pypa/manylinux2014_x86_64

RUN yum -y update && yum -y install \
    curl \
    zlib-devel \
    eigen3-devel \
    mpfr-devel \
    gmp-devel \
    devtoolset-8 \
    && yum clean all

RUN mkdir -p /opt/cmake \
    && curl -LO "https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.sh" \
    && sh cmake-3.16.2-Linux-x86_64.sh  --skip-license --prefix=/opt/cmake \
    && rm -f cmake-3.16.2-Linux-x86_64.sh

# yum install boost-devel installs boost 1.53 and copy is the only way to install headers only boost
RUN curl -LO "https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.tar.gz" \
    && tar xf boost_1_73_0.tar.gz \
    && cd boost_1_73_0 \
    && ./bootstrap.sh \
    && ls \
    && cp -r boost /usr/local/include/ \
    && cd .. \
    && rm -rf boost

ADD install_cgal.sh /
RUN chmod +x install_cgal.sh && ./install_cgal.sh

ADD build-requirements.txt /

RUN /opt/python/cp36-cp36m/bin/pip install twine\
    && /opt/python/cp36-cp36m/bin/pip install -r build-requirements.txt\
    && /opt/python/cp37-cp37m/bin/pip install -r build-requirements.txt\
    && /opt/python/cp38-cp38/bin/pip install -r build-requirements.txt\
    && /opt/python/cp39-cp39/bin/pip install -r build-requirements.txt\
    && /opt/python/cp310-cp310/bin/pip install -r build-requirements.txt

ENV PYTHON36="/opt/python/cp36-cp36m/"
ENV PYTHON37="/opt/python/cp37-cp37m/"
ENV PYTHON38="/opt/python/cp38-cp38/"
ENV PYTHON39="/opt/python/cp39-cp39/"
ENV PYTHON310="/opt/python/cp310-cp310/"

ENV PATH="/opt/cmake/bin:${PATH}"
ENV PATH="/opt/rh/devtoolset-8/root/usr/bin:${PATH}"
