# Builds gudhi/ci_for_gudhi on Docker Hub
FROM ubuntu:24.04

# DEBIAN_FRONTEND=noninteractive is used to prevent installation of
# package tzdata to ask for timezone
ENV DEBIAN_FRONTEND=noninteractive

# Required for Gudhi compilation
RUN apt-get update && apt-get install -y make \
    git \
    g++ \
    cmake \
    graphviz \
    texlive-full \
    biber \
    doxygen \
    latexmk

# apt clean up
RUN apt-get autoremove && apt-get clean && rm -rf /var/lib/apt/lists/*
