# Builds gudhi/ci_for_gudhi_wo_cgal on Docker Hub
FROM ubuntu:24.04

# DEBIAN_FRONTEND=noninteractive is used to prevent installation of
# package tzdata to ask for timezone
ENV DEBIAN_FRONTEND=noninteractive

# Required for Gudhi compilation
RUN apt update && apt install -y make \
    git \
    g++ \
    cmake \
    perl \
    libboost-all-dev \
    python3 \
    python3-venv \
    xz-utils \
    curl

# PEP668: work in a virtual environment
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN mkdir /home/ubuntu/install
ADD build-requirements.txt /home/ubuntu/install/
ADD test-requirements.txt /home/ubuntu/install/
RUN python -m pip install -r /home/ubuntu/install/build-requirements.txt
RUN python -m pip install -r /home/ubuntu/install/test-requirements.txt

# Try to do the same layers as Dockerfile_for_circle_ci_image
RUN curl -LO "https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz" \
    && tar xf eigen-3.4.0.tar.gz

# apt clean up
RUN apt autoremove && rm -rf /var/lib/apt/lists/*
